steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lms-service-user', '.']

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lms-service-user']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'lms-service-user'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lms-service-user'
      - '--region'
      - 'asia-southeast1'
      # You can customize the following flags as per your requirements
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'

# Optionally, you can include additional steps for running tests, linting, etc.